branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: feature/
  - label: '*'
    prefix: feature/
gitSafeReplacementChar: '-'
branchName: 'SB${repository.name[7,4]}${issue.number}-${issue.title[0,64],}'
autoCloseIssue: true