branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: feature/
  - label: '*'
    prefix: feature/
gitSafeReplacementChar: '-'
branchName: 'SB-${issue.number%4}-${issue.title[0,64],}'
autoCloseIssue: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
prSkipCI: true