title: Subhamay Bhattacharyya
description: Subhamay's personal website and blog
author: Subhamay

# Layout settings
hide_header: false
hide_hero: false
# hide_toc: true  # Uncomment to hide TOC globally

# Nav (optional)
data:
  nav:
    items: []

# Build settings
markdown: kramdown
theme: minima