title: Subhamay Bhattacharyya
description: Test site for Jekyll layout
author: Subhamay

# Layout settings
hide_header: false
hide_hero: false
# hide_toc: true  # Uncomment to hide TOC globally

# Nav (optional)
data:
  nav:
    items:
      - title: GitHub
        url: https://github.com/subhamay-bhattacharyya

# Build settings
markdown: kramdown
theme: minima